weights: .\runs\train\exp6\last.pt
cfg: ''
data: data/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 30
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: 'true'
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: ''
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.1
upload_dataset: false
bbox_interval: -1
save_period: 10
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs\train\exp20
total_batch_size: 16
